version: '3.9'
services:
  db:
    image: postgres:15.1-alpine
    # restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - finance-db:/var/lib/postgresql/data
volumes:
  finance-db:
